version: '3.4'

services:
  php:
    container_name: php-$PROJECT_NAME
    restart: always
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/app
      - .docker/conf/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - database
      - proxy
      - rabbitmq-network

  nginx:
    container_name: nginx-$PROJECT_NAME
    restart: always
    build:
      context: .docker/nginx
    volumes:
      - .:/var/www/app
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - proxy
    expose:
      - 80
      - 443
    depends_on:
      - php
    tty: true
    links:
      - php
    environment:
      VIRTUAL_HOST: $WEB_NAME
      LETSENCRYPT_HOST: $WEB_NAME
      LETSENCRYPT_EMAIL: $EMAIL

  php-email:
    container_name: php-email-$PROJECT_NAME
    restart: always
    build:
      context: .
      dockerfile: .docker/php-email/Dockerfile.dev
    volumes:
      - .:/var/www/app
      - .docker/conf/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - database
      - rabbitmq-network

  composer:
    container_name: composer-$PROJECT_NAME
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "composer update --ignore-platform-reqs --no-dev &&
             rm -rf /var/www/app/temp/*"

networks:
  proxy:
    external:
      name: nginx-proxy
  database:
    external:
      name: database-network
  rabbitmq-network:
    external:
      name: rabbitmq-network